name: Development
on: [push]
jobs: 
  run-linters:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run lint
        run: npm lint
      - name: Run build
        run: npm build
